import type { Metadata } from 'next';
import Link from 'next/link';
import { SitePage } from '@/components/layout/site-page';
import { FaqList } from './faq-list';
import { env } from '@/lib/env';

export const metadata: Metadata = {
  title: `FAQ — ${env.NEXT_PUBLIC_APP_NAME}`,
  description: 'Answers about listings, roommates, Need Now, chat, and your data.',
};

const FAQS: { q: string; a: string }[] = [
  {
    q: 'Is this only for students?',
    a: 'The product is built around colleges and campuses. You pick a college to search nearby flats, PGs, and roommate posts. Landlords and partners list through a separate portal.',
  },
  {
    q: 'How do I search for a flat?',
    a: 'Use home search or Browse Flats. Filter by college, keywords (area, BHK), then open a listing. You can save favorites and express interest without leaving the app.',
  },
  {
    q: 'What is Need Now?',
    a: 'Need Now is a 24-hour housing requirement. You post what you need; nearby students and listings can respond before the timer runs out. Expired posts stop taking interest.',
  },
  {
    q: 'How do roommates work?',
    a: 'Browse roommate posts, express interest, and chat in-app. Posts are for genuine personal needs — no promotional banners, QR codes, or phone numbers in photos.',
  },
  {
    q: 'Why can’t I see a phone number on the listing?',
    a: 'Direct numbers stay hidden until contact sharing is approved. Owners can require chat-only, a request, a delay for verified users, or a fallback contact. Access is temporary and view-limited.',
  },
  {
    q: 'How do I download or delete my data?',
    a: 'Signed-in users can export or request erasure from Settings → Your data. Export jobs are generated by the API; erasure needs an explicit PURGE confirmation.',
  },
  {
    q: 'How do I report someone?',
    a: 'Use in-app report from chat or the listing/roommate flow. Do not paste contact details in photos or chat if you want them kept private.',
  },
];

export default function FaqPage() {
  return (
    <SitePage
      title="Frequently asked questions"
      description={`How ${env.NEXT_PUBLIC_APP_NAME} works for search, roommates, Need Now, and privacy.`}
    >
      <FaqList items={FAQS} />
      <p>
        Still stuck?{' '}
        <Link href="/contact" className="font-medium text-primary hover:underline">
          Contact us
        </Link>
        {' '}or read the{' '}
        <Link href="/privacy" className="font-medium text-primary hover:underline">
          privacy policy
        </Link>
        .
      </p>
    </SitePage>
  );
}
